#!/bin/bash

# @requires: imagemagick

source $HOME/.config/eww/var.conf
cache_folder="/tmp/eww/thumbnails"

create_thumbnails(){
    if [ -d "$cache_folder" ]; then
        rm -r "$cache_folder"
    fi
    mkdir -p "$cache_folder"

    for file in $SET_BG/*; do
        convert $file -resize 10% $cache_folder/$(basename "$file")
    done
}
get_bg(){
    json="["
    first="true"

    for file in $SET_BG/*; do
        if [ -f "$file" ]; then
            if [ "$first" = "true" ]; then
                json+="{\"style\":\"background-image: url('$cache_folder/$(basename "$file")')\", \"path\":\"$SET_BG$(basename "$file")\"}"
                first="false"
            else
                json+=",{\"style\":\"background-image: url('$cache_folder/$(basename "$file")')\", \"path\":\"$SET_BG$(basename "$file")\"}"
            fi
        fi
    done

    json+="]"
    echo $json | jq -r .
}
chg_bg(){
    swww img $1
}
case $1 in
    cache)
        create_thumbnails
        ;;
    get)
        get_bg
        ;;
    set)
        chg_bg $2
        ;;
esac