#!/bin/bash
connect_device() {
    device_address=$2
    device_name=$1
    echo "Подключение к устройству: $device_name ($device_address)"
    hcitool cc $device_address
    if [ $? -eq 0 ]; then
        notify-send "Подключено" "$device_name"
    else
        notify-send "Не удалось подключиться к устройству." "$device_name"
    fi
}
scan_devices() {
    devices=$(hcitool scan | awk 'NR>1{if ($1!="Scanning") {if (sep) {printf ",\n"} printf "{\"address\":\"%s\", \"name\":\"%s\"}", $1, $2; sep=1}}')
    echo "[$devices]"
}


while true; do
  btStatus=$(eww get bluetooth_state)
  if [[ $btStatus == 'on' ]]; then
    deviceList=$(scan_devices)
    eww update list_devices="$deviceList"
    echo "$deviceList"
  fi
  sleep 60
done