#!/bin/bash

temp_folder="/tmp"
default_style="background-image: url('images/ui/default.jpg');"
player_status=$(cmus-remote -C status | grep status | awk {'print $2'})
player_tags=$(cmus-remote -Q)

check_available() {
  if ! pgrep -x "cmus" > /dev/null; then
    echo "off"
  else
    echo "on"
  fi
}
get_tag(){
    tag=$(echo "$player_tags" | grep -w "tag $1" | cut -d ' ' -f 3-)
    echo $tag
}
get_abs_duration(){
    echo $(echo "$player_tags" | grep -w "duration" | awk '{ print $2}')
}
get_abs_position(){
  abs_position=$(echo "$player_tags" | grep -w "position" | awk '{ print $2}')
  if [[ $abs_position -le 1 ]]; then
    get_cover
  fi
  echo $abs_position
}
convert(){
  abs_value=$(echo "$player_tags" | grep -w "$1" | awk '{ print $2}')
  minutes=$((abs_value / 60))
  seconds=$((abs_value % 60))
  converted_value=$(printf "%d:%02d" $minutes $seconds)
  echo "$converted_value"
}
get_cover(){
  mp3_file=`echo "$player_tags" | grep "file" | awk -F 'file ' '{print $2}'`
  rm -f "$temp_folder/cover.jpg"
  ffmpeg -i "$mp3_file" -an -vcodec copy "$temp_folder/cover.jpg" 2>/dev/null 
}
get_style(){
  style=$([ -e "$temp_folder/cover.jpg" ] && echo "background-image: url('$temp_folder/cover.jpg');" || echo $default_style)
  echo $style
}
track_info(){
  if [[ $(check_available) == "on" ]]; then
    local json=$(jq -n \
      --arg available "$(check_available)" \
      --arg status $player_status \
      --arg title "$(get_tag title)" \
      --arg artist "$(get_tag artist)" \
      --arg album "$(get_tag album)" \
      --arg abs_duration "$(get_abs_duration)" \
      --arg duration "$(convert $(get_abs_duration))" \
      --arg abs_position "$(get_abs_position)" \
      --arg position "$(convert $(get_abs_position))" \
      --arg style "$(get_style)" \
      '{available: $available, status: $status, title: $title, artist: $artist, album: $album, album: $album, abs_duration: $abs_duration, abs_position: $abs_position, duration: $duration, position: $position, style: $style}')
  else
    local json=$(jq -n --arg available "$(check_available)" '{available: $available}')
  fi
  echo "$json" | jq -r .
}
track_info
