#!/bin/bash

temp_folder="/tmp/eww/covers"

if [ ! -d "$temp_folder" ]; then
  mkdir -p "$temp_folder"
fi

default_style="background-image: url('images/ui/default.jpg');"
player_status=$(cmus-remote -C status | grep status | awk {'print $2'})
player_tags=$(cmus-remote -Q)

check_available() {
  pgrep -x "cmus" > /dev/null && echo "on" || echo "off"
}
get_tag(){
    tag=$(echo "$player_tags" | grep -w "tag $1" | cut -d ' ' -f 3-)
    echo $tag
}
get_value(){
  value=$(echo "$player_tags" | grep -w "$1" | awk '{ print $2}')
  echo $value
}
get_style(){
  mp3_file=`echo "$player_tags" | grep "file" | awk -F 'file ' '{print $2}'`
  if [[ ! -f "$temp_folder/$1.jpg" ]]; then
    ffmpeg -i "$mp3_file" -an -vcodec copy "$temp_folder/$1.jpg" 2>/dev/null
  fi
  style=$([ -e "$temp_folder/$1.jpg" ] && echo "background-image: url('$temp_folder/$1.jpg');" || echo $default_style)
  echo $style
}
track_info(){
  local available=$(check_available)
  if [[ $(echo $available) == "on" ]]; then
    local title=$(get_tag title)
    local artist=$(get_tag artist)
    local album=$(get_tag album)
    local duration=$(get_value duration)
    local position=$(get_value position)
    local style=$(get_style $title)
    local json=$(jq -n \
      --arg available $available \
      --arg status $player_status \
      --arg title "$title" \
      --arg artist "$artist" \
      --arg album "$album" \
      --arg abs_duration "$abs_duration" \
      --arg duration "$duration" \
      --arg abs_position "$abs_position" \
      --arg position "$position" \
      --arg style "$style" \
      '{available: $available, status: $status, title: $title, artist: $artist, album: $album, album: $album, duration: $duration, position: $position, style: $style}')
  else
    local json=$(jq -n --arg available $available '{available: $available}')
  fi

  echo "$json" | jq -r .
}
track_info
