#!/bin/bash
source $HOME/.config/eww/var.conf

get_vars(){
    local lang=$(echo $SET_LANG)
    local battery=$(echo $SET_BAT)
    local max_brightness=$(brightnessctl | grep Max | awk '{print $3}')
    local sensor=$(echo $SET_SENSOR)
    local scr_path=$(echo $SET_SCR)
    local json="{\"lang\": \"$lang\", \"battery\": \"$battery\", \"max_brightness\": \"$max_brightness\", \"sensor\": \"$sensor\", \"scr_path\": \"$scr_path\"}"
    echo "$json" | jq -r .
}
get_srings(){
    local lang=$(echo $SET_LANG)
    local file="$HOME/.config/eww/jsons/string.json"

    if [ "$lang" == "EN" ]; then
        jq -r '.stings | to_entries | map({(.key): .value[0]}) | add' "$file"
    elif [ "$lang" == "RU" ]; then
        jq -r '.stings | to_entries | map({(.key): .value[1]}) | add' "$file"
    fi
}

case $1 in
    vars)
        get_vars
        ;;
    strings)
        get_srings
        ;;
esac

