#!/bin/bash
source $HOME/.config/eww/var.conf

get_vars(){
    local json=$(jq -n \
      --arg lang "$(echo $SET_LANG)" \
      --arg battery "$(echo $SET_BAT)" \
      --arg max_brightness "$(brightnessctl | grep Max | awk '{print $3}')" \
      --arg sensor "$(echo $SET_SENSOR)" \
      --arg scr_path "$(echo $SET_SCR)" \
      --arg user "$(echo "$(whoami)")" \
      '{user: $user, lang: $lang, battery: $battery, max_brightness: $max_brightness, sensor: $sensor, scr_path: $scr_path}')
    echo "$json" | jq -r .
}
get_strings(){
    local lang=$(echo $SET_LANG)
    local file="$HOME/.config/eww/jsons/string.json"

    if [ "$lang" == "EN" ]; then
        jq -r '.strings | to_entries | map({(.key): .value[0]}) | add' "$file"
    elif [ "$lang" == "RU" ]; then
        jq -r '.strings | to_entries | map({(.key): .value[1]}) | add' "$file"
    fi
}

case $1 in
    vars)
        get_vars
        ;;
    strings)
        get_strings
        ;;
esac

