#!/usr/bin/sh
source $HOME/.config/eww/var.conf

switch_layout() {
    	hyprctl switchxkblayout $SET_KB next
		LAYOUT=$(hyprctl devices | grep -A 2 "$SET_KB" | grep keymap | awk '{ print $3 }')
}
get_layout() {
	LAYOUT=$(hyprctl devices | grep -A 2 "$SET_KB" | grep keymap | awk '{ print $3 }')
	[[ "$LAYOUT" == "English" ]] && echo "EN" || echo "RU" 
}
set_layout() {
	hyprctl switchxkblayout $SET_KB 0   
}

if [[ "$1" == "swkb" ]]; then
	switch_layout
elif [[ "$1" == "getkb" ]]; then
	get_layout
elif [[ "$1" == "setkb" ]]; then
	set_layout
fi

