#!/bin/bash
source $HOME/.config/eww/var.conf

file="$HOME/.config/eww/jsons/weather_codes.json"

city=$SET_CITY
api_key=$SET_API_key

if [[ $SET_LANG == 'RU' ]]; then
    language='ru-ru'
else
    language='en-en'
fi


URL="http://dataservice.accuweather.com/forecasts/v1/daily/5day/${city}?apikey=${api_key}&language=${language}&details=true&metric=true"

headers='User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

# Загрузка данных из файла 'var' УКАЗАТЬ ПРАВИЛЬНЫЙ ПУТЬ
icons_json=$(cat $file | jq -r '.codes')

get_json() {
    response=$(curl -s -H "${headers}" "${URL}")

    if [ $? -eq 0 ]; then
        create_new_json "${response}"
    else
        echo "[]" | jq -r .
        exit 1
    fi
}

create_new_json() {
    in_data="${1}"
    out_data=()
    number=0
    while read -r line; do
        # формат даты
        date_raw=$(echo "${line}" | jq -r '.Date' | cut -d'T' -f1)
        date=$(date -d "${date_raw}" '+%d.%m')
        ((number++))
        prec=$(echo "${line}" | jq -r '.Day.PrecipitationProbability' | sed 's/null/0/g' | awk '{printf("%.0f%%\n", $1)}')
        
        if [[ $SET_LANG == "RU" ]]; then
            wind_speed=$(echo "${line}" | jq -r '.Day.Wind.Speed.Value' | awk '{printf("%.1f м/с\n", $1 / 3.6)}')
            wind_dir=$(echo "${line}" | jq -r '.Day.Wind.Direction.Localized')
        else
            wind_speed=$(echo "${line}" | jq -r '.Day.Wind.Speed.Value' | awk '{printf("%.1f m/s\n", $1 / 3.6)}')
            wind_dir=$(echo "${line}" | jq -r '.Day.Wind.Direction.English')
        fi

        temp_max=$(echo "${line}" | jq -r '.Temperature.Maximum.Value' | awk '{printf("%.1f°C\n", $1)}')
        temp_min=$(echo "${line}" | jq -r '.Temperature.Minimum.Value' | awk '{printf("%.1f°C\n", $1)}')
        icon=$(echo "${line}" | jq -r '.Day.Icon')
        
        # Получение значений из файла 'var' для icon и icon_phrase
        icon_values=$(echo "${icons_json}" | jq -r '.["'"$icon"'"]')
        icon_value=$(echo "${icon_values}" | jq -r '.[0]')
        if [[ $SET_LANG == "RU" ]]; then
            icon_phrase=$(echo "${icon_values}" | jq -r '.[1]')
        else 
             icon_phrase=$(echo "${icon_values}" | jq -r '.[2]')
        fi
        
        if [ -z "$icon_value" ]; then
            icon_value="$icon"
        fi

        if [ -z "$icon_phrase" ]; then
            icon_phrase="$icon_value"
        fi

        out_data+=("{\"num\": \"${number}\",\"date\": \"${date}\", \"prec\": \"${prec}\", \"wind_speed\": \"${wind_speed}\", \"wind_dir\": \"(${wind_dir})\", \"temp_max\": \"${temp_max}\", \"temp_min\": \"${temp_min}\", \"icon\": \"${icon_value}\", \"icon_phrase\": \"${icon_phrase}\"}")
    done <<< "$(echo "${in_data}" | jq -c '.DailyForecasts[]')"
    
    echo "["
    for ((i=0; i<${#out_data[@]}; i++)); do
        echo -n "${out_data[i]}"
        if [ $i -lt $((${#out_data[@]}-1)) ]; then
            echo ","
        fi
    done
    echo "]"
}

get_json