#!/bin/bash
eww_output=$(eww windows)

window_status(){
  declare -A results
  window_list=("control" "screenshot" "chg_bg" "calendar" "net_list" "launcher") 
  for item in "${window_list[@]}"; do
    state=$(echo "$eww_output" | grep "$item" | cut -c1)
    if [[ "$state" == "*" ]]; then
      results["$item"]="close"
    else
      results["$item"]="open"
    fi
  done
  json="{"
  for key in "${!results[@]}"; do
    json+="\"$key\":\"${results[$key]}\", "
  done
  json="${json%, *} }"
  echo "$json" | jq -r .
}
toggle_window(){
  local state=$(echo "$eww_output" | grep "$1" | cut -c1)
  if [[ "$state" == "*" ]]; then
    echo $(eww close $1)
  else
    echo $(eww open $1)
  fi
}

case "$1" in
  "status")
    window_status
    ;;
  "toggle")
    toggle_window $2
    ;;
esac